// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameEvent = "event"

// Event mapped from table <event>
type Event struct {
	Eid              int32     `gorm:"column:eid;primaryKey;autoIncrement:true" json:"eid"`
	ID               string    `gorm:"column:id;not null" json:"id"`
	EventName        string    `gorm:"column:event_name;not null" json:"event_name"`
	EventDescription string    `gorm:"column:event_description;not null" json:"event_description"`
	Tags             string    `gorm:"column:tags" json:"tags"`
	Picture          string    `gorm:"column:picture" json:"picture"`
	EventURL         string    `gorm:"column:event_url;not null" json:"event_url"`
	EventSpeaker     string    `gorm:"column:event_speaker;not null" json:"event_speaker"`
	EventTime        time.Time `gorm:"column:event_time;not null" json:"event_time"`
	UpdateAt         time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP" json:"update_at"`
	CreatedAt        time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName Event's table name
func (*Event) TableName() string {
	return TableNameEvent
}
