// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProject = "project"

// Project mapped from table <project>
type Project struct {
	Pid                int32     `gorm:"column:pid;primaryKey;autoIncrement:true" json:"pid"`
	ID                 string    `gorm:"column:id;not null" json:"id"`
	ProjectName        string    `gorm:"column:project_name;not null" json:"project_name"`
	Pinned             bool      `gorm:"column:pinned;not null" json:"pinned"`
	ProjectDescription string    `gorm:"column:project_description;not null" json:"project_description"`
	Tags               string    `gorm:"column:tags" json:"tags"`
	LogoPicture        string    `gorm:"column:logo_picture" json:"logo_picture"`
	GithubURL          string    `gorm:"column:github_url" json:"github_url"`
	SiteURL            string    `gorm:"column:site_url" json:"site_url"`
	OwnerEmail         string    `gorm:"column:owner_email" json:"owner_email"`
	UpdateAt           time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP" json:"update_at"`
	CreatedAt          time.Time `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
