// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserDetail = "user_detail"

// UserDetail mapped from table <user_detail>
type UserDetail struct {
	UdUserID            int32     `gorm:"column:ud_user_id;primaryKey;autoIncrement:true" json:"ud_user_id"`
	Gender              string    `gorm:"column:gender" json:"gender"`
	Birthday            time.Time `gorm:"column:birthday" json:"birthday"`
	UserHasTag          string    `gorm:"column:user_has_tag" json:"user_has_tag"`
	ProfilePicture      string    `gorm:"column:profile_picture" json:"profile_picture"`
	Interests           string    `gorm:"column:interests" json:"interests"`
	PersonalDescription string    `gorm:"column:personal_description" json:"personal_description"`
	Location            string    `gorm:"column:location" json:"location"`
	RelationshipStatus  string    `gorm:"column:relationship_status" json:"relationship_status"`
	LookingFor          string    `gorm:"column:looking_for" json:"looking_for"`
	PrivacySettings     string    `gorm:"column:privacy_settings" json:"privacy_settings"`
	SocialLinks         string    `gorm:"column:social_links" json:"social_links"`
	IsBanned            bool      `gorm:"column:is_banned" json:"is_banned"`
}

// TableName UserDetail's table name
func (*UserDetail) TableName() string {
	return TableNameUserDetail
}
